name: yam_api
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4

  crypto: ^3.0.2
  json_annotation: ^4.5.0
  device_info_plus: ^8.0.0
  uuid: ^3.0.6
  cryptography: ^2.5.0
  intl: ^0.18.0
  xml: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  json_serializable: ^6.2.0
  build_runner: ^2.1.10
